sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - '11.10.1'
  - '10'
  - '9'
  - '8'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test -- --ci --verbose --coverage
